# Generated by Django 3.2.4 on 2021-07-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210701_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='user',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='prerequisite',
            old_name='user',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='course',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField()),
                ('video_id', models.CharField(max_length=30)),
                ('is_preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
